---
- hosts: localhost
  sudo: yes
  tasks:
    - name: Create the users
      user: name={{ item }}
      with_items: "{{ users }}"

    - name: Install apt packages
      apt: name={{ item }} state=latest
      with_items: "{{ apt_packages }}"
